# -*- coding: utf-8 -*-
"""231A_Team.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rxqshAdO3No_cc1MpVppBq5LAhXW-6_
"""

n = int(input())
count = 0

for i in range(n):
  matrix = list(map(int, input().split()))

  if sum(matrix) >= 2:
        count += 1
print(count)