# -*- coding: utf-8 -*-
"""Watermelon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NX0qYMvgFtJcWrB-WiBjme7KK9si8qh0
"""

def watermelon_division():
  weight = int(input())
  if weight%2==0 and weight!=2:
    return "YES"

  else:
    return "NO"

print(watermelon_division())