# -*- coding: utf-8 -*-
"""Way Too Long Words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NX0qYMvgFtJcWrB-WiBjme7KK9si8qh0
"""

n = int(input())
for i in range(n):
    word = input()
    if len(word)<=10:
      print(word)
    else:
      first_char = word[0]
      last_char = word[-1]
      num_between= len(word)-2
      print(f"{first_char}{num_between}{last_char}")