# -*- coding: utf-8 -*-
"""Boy or Girl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

name = input().lower()

unique_char = len(set(name))


if unique_char%2==0:
  print("CHAT WITH HER!")
else:
  print("IGNORE HIM!")