# -*- coding: utf-8 -*-
"""Domino piling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGh6HMjffdGqKFR7E1_5cLXejTJOVXyY
"""

m, n = map(int, input().split())
product = m*n
xx = product//2
print(xx)