# -*- coding: utf-8 -*-
"""Helpful Maths.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

s = input()
numbers = s.split('+')

numbers.sort()

print('+'.join(numbers))