# -*- coding: utf-8 -*-
"""Petya and Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

s1 = input().lower()
s2 = input().lower()


if s1 == s2:
  print(0)
elif s1>s2:
  print(1)
elif s1<s2:
  print(-1)