# -*- coding: utf-8 -*-
"""Soldier and Bananas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

k, n, w =map(int, input().split())
price = 0
for i in range(1,w+1):
  price += k * i

borrow = price - n
if borrow < 0:
    borrow = 0
print(borrow)