# -*- coding: utf-8 -*-
"""Stones on the Table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

n = int(input())
s = input()

count = 0
for i in range(1, n):
    if s[i] == s[i - 1]:
        count += 1

print(count)