# -*- coding: utf-8 -*-
"""Word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

s = input()

count_lower = 0
count_upper = 0
for i in s:
  if i.islower():
    count_lower+=1
  if i.isupper():
    count_upper += 1
if count_upper == count_lower:
  s = s.lower()
elif count_upper > count_lower:
  s = s.upper()
elif count_lower>count_upper:
  s = s.lower()



print(s)