# -*- coding: utf-8 -*-
"""Word Capitalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

word = input()

word = word[0].upper() + word[1:]


print(word)