# -*- coding: utf-8 -*-
"""Wrong subtraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyxAGbc3GEfX43Jdo7e0FPsVdSxo8mZM
"""

n, k = map(int, input().split())

for i in range(k):
  if n%10 !=0:
    n -=1
  else:
    n//=10
print(n)